import { strict as assert } from "node:assert";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import Home from "../../app/page";
import { FamilyLobby } from "../../app/family/FamilyLobby";
const home = renderToStaticMarkup(createElement(Home));
for (const label of ["혼자 하기", "가족 농장", "맵 편집기"]) assert.ok(home.includes(label));
const lobby = renderToStaticMarkup(createElement(FamilyLobby, { onBack: () => {}, onEnter: () => {} }));
for (const label of ["농장 만들기", "초대 코드", "닉네임", "최근 참가한 가족 농장"]) assert.ok(lobby.includes(label));
assert.ok(lobby.includes('maxLength="20"') || lobby.includes('maxlength="20"'));
console.log("Family lobby: single/family/editor entry and room forms rendered");
