import {strict as assert} from "node:assert";
import { normalizeProgress,talkToNpc,relationshipLevel } from "../npc/progress";
import { normalizeSaveData } from "../domain";
import { familyTestDB } from "./family-db";
import { FamilyRooms } from "../../server/family/rooms";
import { FamilyProgress } from "../../server/family/progress";
import { FamilyState } from "../../server/family/state";
import { NpcController } from "../npc/NpcController";
import { NPC_DEFINITIONS } from "../npc/definitions";
import { MapRegistry } from "../maps/MapRegistry";
const local=normalizeProgress(null);
talkToNpc(local,"daon",1,360,1);talkToNpc(local,"daon",1,360,1);assert.equal(local.relationships.daon.points,10);
talkToNpc(local,"daon",2,360,2);assert.equal(local.relationships.daon.points,20);assert.equal(relationshipLevel(20),"아는 사이");
talkToNpc(local,"daon",1,360,29);assert.equal(local.relationships.daon.points,30,"season rollover has a fresh day serial");
assert.equal(normalizeSaveData({version:4,day:1})!.playerProgress!.relationships.daon.points,0);
assert.equal(normalizeSaveData({version:1})!.playerProgress!.relationships.daon.points,0);
assert.equal(normalizeSaveData({version:4,playerProgress:local})!.playerProgress!.relationships.daon.points,30);
assert.equal(normalizeProgress({relationships:{daon:{points:-50,dialogue:{cursor:NaN}}}}).relationships.daon.points,0);
const {db,close}=familyTestDB();const now=()=>1000000;
try {
 const rooms=new FamilyRooms(db,now),service=new FamilyProgress(db,now),state=new FamilyState(db,now);
 const a=await rooms.create("npc-a","주민 농장","가족 A");await rooms.join("npc-b",a.room.inviteCode,"가족 B");
 await state.read("npc-a",a.room.id);
 const actor=new NpcController(NPC_DEFINITIONS,new MapRegistry()).sample(1,360).find(p=>p.npcId==="daon")!;
 const pose={...actor,selectedTool:"hand",moving:false};
 let progress=await service.readProgress("npc-a",a.room.id);
 const first=await service.interact("npc-a",a.room.id,progress.revision,{kind:"talk",npcId:"daon"},pose);
 assert.equal(first.progress.data.relationships.daon.points,10);
 assert.equal((await service.readProgress("npc-b",a.room.id)).data.relationships.daon.points,0);
 await assert.rejects(()=>service.interact("npc-a",a.room.id,0,{kind:"talk",npcId:"daon"},pose));
 const again=await service.interact("npc-a",a.room.id,first.progress.revision,{kind:"talk",npcId:"daon"},pose);
 assert.equal(again.progress.data.relationships.daon.points,10);
 const reconnected=new FamilyProgress(db,now);assert.equal((await reconnected.readProgress("npc-a",a.room.id)).data.relationships.daon.points,10);
 await assert.rejects(()=>service.readProgress("outsider",a.room.id));
 await assert.rejects(()=>service.interact("npc-a",a.room.id,again.progress.revision,{kind:"talk",npcId:"daon"},{...pose,mapId:"farm"}));
 await db.prepare("UPDATE family_state SET world_json=json_set(world_json,'$.day',2,'$.daySerial',2),revision=revision+1 WHERE room_id=?").bind(a.room.id).run();
 const day2=await service.interact("npc-a",a.room.id,again.progress.revision,{kind:"talk",npcId:"daon"},pose);
 assert.equal(day2.progress.data.relationships.daon.points,20);
 const race=await Promise.allSettled([1,2].map(()=>service.interact("npc-a",a.room.id,day2.progress.revision,{kind:"talk",npcId:"daon"},pose)));
 assert.equal(race.filter(r=>r.status==="fulfilled").length,1);
 await rooms.manage("npc-b",a.room.id,"leave");
 assert.equal((await db.prepare("SELECT COUNT(*) AS count FROM family_player_progress").first<{count:number}>())!.count,1);
 await rooms.manage("npc-a",a.room.id,"delete");
 assert.equal((await db.prepare("SELECT COUNT(*) AS count FROM family_player_progress").first<{count:number}>())!.count,0);
} finally {close();}
console.log("NPC progress: daily bonus, rollover, legacy saves, personal isolation, reconnect, CAS, membership/cascade passed");
